# pluger settings
pluger_repo=${PLUGER_REPO:-https://github.com/cao7113/rbenv-pluger.git}
pluger_root=${PLUGER_ROOT:-$rbenv_plugins_root/rbenv-pluger}
[ -d $pluger_root ] || {
  if [ -n "$vagrant_vm" ];then
    echo ==using local /vagrant/rbenv-pluger
    sudo ln -s /vagrant/rbenv-pluger $pluger_root
  else
    git clone $pluger_repo $pluger_root
  fi

  [ -d $rbenv_plugins_root/rbenv-vars ] && {
    ln -sb $pluger_root/etc/dot.rbenv-vars $rbenv_root/vars
  }

  [ -d $rbenv_plugins_root/rbenv-default-gems ] && {
    ln -sb $pluger_root/etc/default-gems $rbenv_root/default-gems
  }

  gemrc_file=$pluger_root/etc/dot.gemrc
  if [ -f $gemrc_file ];then
    [ -e ~/.gemrc ] || ln -sb $gemrc_file ~/.gemrc
    [ -e /etc/gemrc ] || sudo ln -sb $gemrc_file /etc/gemrc
  fi

  for f in irbrc railsrc rails.irbrc pryrc; do
    if [ -e $pluger_root/etc/dot.$f ];then
      ln -sb $pluger_root/etc/dot.$f ~/.$f 
    fi
  done
}

## set shell init file
global_rbenv_file=/etc/profile.d/rbenv.sh
[ -f $global_rbenv_file ] || {
  tmpfile=/tmp/rbenv.rc
  cat <<-RCFILE >$tmpfile
#set rbenv generated by $0 on `date`
[ -n "\$RBENV_ROOT" ] && return #avoid twice sourced
export RBENV_ROOT=$rbenv_root #required
export PATH=\$RBENV_ROOT/shims:\$RBENV_ROOT/bin:\$PATH
RCFILE
  sudo mv -b $tmpfile $global_rbenv_file
  echo create global rbenv file: $global_rbenv_file !
}

## interactive bashrc
init_file=~/.bashrc
grep -q "rbenv" $init_file || {
  tmpfile=/tmp/my_bashrc
  echo "[ -e $global_rbenv_file ] && source $global_rbenv_file" > $tmpfile
  cat $tmpfile $init_file >$tmpfile.tmp && mv -b $tmpfile.tmp $init_file
  echo Set rbenv into file: $init_file, reshell to take effect!
}

## install a ruby
rbenv_bin=$rbenv_root/bin/rbenv
ruby_version=${RUBY_VERSION:-2.2.0}
this_ruby_dir=$rbenv_root/versions/$ruby_version 
if [ -n "$ruby_version" -a -f "$rbenv_plugins_root/ruby-build/share/ruby-build/$ruby_version" ];then
  [ -d $this_ruby_dir ] || {
    export RBENV_ROOT=$rbenv_root  #Note: must set before pluger subcommand used
    eval "$($rbenv_bin vars)"
    $rbenv_bin install -v $ruby_version 
    $rbenv_bin global $ruby_version
    echo Has installed $ruby_version into $this_ruby_dir
  }
fi

echo ==Install new rbox with ruby: $ruby_version from $t0 to `date`
