#!/usr/bin/env bash
# rbox is your own ruby env manager, current rbenv based

run_as=${USER:-vagrant} # current running user
grep -q $run_as /etc/passwd || { echo No user: $run_as; exit 1; }
perm=$run_as:$run_as

## DEPENDENCY CHECKING  todo
# http://www.cyberciti.biz/faq/find-out-if-package-is-installed-in-linux/#debian
function check_pkg(){
  [ $# -lt 1 ] && echo Usage: $FUNCNAME PKG_NAME && return 1
  pkg=$1
  if ! dpkg-query -W -f='${Status} ${Version}\n' "$pkg" >/dev/null; then
    echo Require package: $pkg ...
    exit 1
  fi
}

function check_pkgs(){
  [ $# -lt 1 ] && echo "Usage: $FUNCNAME PKG1 [PKG2 ...]" && return 1
  for p in $@; do
    check_pkg $p
  done
}

check_pkgs git

rbox_root=${RBOX_ROOT:-/rbox}
[ -d $rbox_root ] || {
  cmd="mkdir -p $rbox_root" && $cmd &>/dev/null || sudo $cmd 
}
[ "`stat --format '%U:%G' $rbox_root`" = "$perm" ] || { 
  sudo chown -R $perm $rbox_root
  echo ==make $perm permission to dir: $rbox_root
}
cd $rbox_root

rbenv_repo=${RBENV_REPO:-https://github.com/sstephenson/rbenv.git}
rbenv_root=${RBENV_ROOT:-$rbox_root/rbenv}
rbenv_bin=$rbenv_root/bin/rbenv
echo ==rbenv root: $rbenv_root

[ -d $rbenv_root/.git ] || { 
  git clone $rbenv_repo $rbenv_root 
  mkdir -p $rbenv_root/shims
  mkdir -p $rbenv_root/cache && echo Recommend to use cache for ruby-build install in $rbenv_root/cache
}

rbenv_plugins_root=$rbenv_root/plugins
[ -d $rbenv_plugins_root ] || {
  mkdir -p $rbenv_plugins_root

  rbenv_plugins=(
  https://github.com/sstephenson/rbenv-vars.git
  https://github.com/sstephenson/ruby-build.git
  https://github.com/rkh/rbenv-update.git
  https://github.com/sstephenson/rbenv-gem-rehash.git
  https://github.com/sstephenson/rbenv-default-gems.git
  )

  cd $rbenv_plugins_root

  for plug_repo in ${rbenv_plugins[@]}; do
    git clone $plug_repo && echo ==git cloning $plug_repo ...
  done
}

# pluger settings
pluger_repo=${PLUGER_REPO:-https://github.com/cao7113/rbenv-pluger.git}
pluger_root=${PLUGER_ROOT:-$rbenv_plugins_root/rbenv-pluger}
[ -d $pluger_root ] || {
  git clone $pluger_repo $pluger_root

  [ -d $rbenv_plugins_root/rbenv-default-gems ] && {
    ln -sb $pluger_root/etc/default-gems $rbenv_root/default-gems
  }

  gemrc_file=$pluger_root/etc/dot.gemrc
  if [ -f $gemrc_file ];then
    [ -e ~/.gemrc ] || ln -sb $gemrc_file ~/.gemrc
    [ -e /etc/gemrc ] || sudo ln -sb $gemrc_file /etc/gemrc
  fi

  for f in irbrc railsrc rails.irbrc pryrc; do
    if [ -e $pluger_root/etc/dot.$f ];then
      ln -sb $pluger_root/etc/dot.$f ~/.$f 
    fi
  done
}

## set shell init file
global_rbenv_file=/etc/profile.d/rbenv.sh
[ -f $global_rbenv_file ] || {
  tmpfile=/tmp/rbenv.rc
  cat <<-RCFILE >$tmpfile
#set rbenv generated by $0 on `date`
[ -n "\$RBENV_ROOT" ] && return #avoid twice sourced
export RBENV_ROOT=$rbenv_root #required
export PATH=\$RBENV_ROOT/shims:\$RBENV_ROOT/bin:\$PATH
RCFILE
  sudo mv -b $tmpfile $global_rbenv_file
  echo create global rbenv file: $global_rbenv_file !
}

## interactive bashrc
init_file=~/.bashrc
grep -q "rbenv" $init_file || {
  tmpfile=/tmp/my_bashrc
  echo "[ -e $global_rbenv_file ] && source $global_rbenv_file" > $tmpfile
  cat $tmpfile $init_file >$tmpfile.tmp && mv -b $tmpfile.tmp $init_file
  echo Set rbenv into file: $init_file, reshell to take effect!
}

## install a ruby
ruby_version=${RUBY_VERSION:-2.2.0}
if [ -n "$ruby_version" -a -f "$rbenv_plugins_root/ruby-build/share/ruby-build/$ruby_version" ];then
  this_ruby_dir=$rbenv_root/versions/$ruby_version 
  [ -d $this_ruby_dir ] || {
    export RUBY_BUILD_MIRROR_URL=http://ruby.taobao.org/mirrors/ruby/ 
    export CONFIGURE_OPTS="--disable-install-doc" 

    RBENV_ROOT=$rbenv_root $rbenv_bin install -kv $ruby_version 
    $rbenv_bin global $ruby_version
    echo Has installed $ruby_version into $this_ruby_dir
  }
fi

echo Ok, all things have done now with a new ruby version: $ruby_version as global! 
